### ISSUE TITLE
Asset Container [assets] not found

### ISSUE THREAD

**Issue by fitzage** [cnj-digital/seotamic#6]
1. I installed this plugin, and then clicking on pages in the control panel gave me an `Asset Container [assets] not found` error as did clicking on the Seotamic settings.
2. I published the config and changed the default asset container to `main` which is what I have on this site.
3. This fixed the problem when clicking on the Seotamic settings, but did not fix the problem when clicking on pages.

Ensuring I have a container called “assets” fixes this problem, but there are two issues here:
1. The plugin shouldn’t depend on having an asset container of a specific name in the config, and
2. Even after changing that name, there is something in the plugin that is still looking for it by that name

**Comment by martink635** [comment]
Thanks for reporting this, missed the hardcoded assignment, fixed in latest release

**Comment by SophieNikki** [comment]
I still have this error even when I specific installed version 2.0.2 
How can I fix it?

**Comment by connor11528** [comment]
I have also encountered this issue. Is there a fix? 

<img width="1141" alt="Screen Shot 2021-05-02 at 12 03 34 PM" src="https://user-images.githubusercontent.com/3578908/116824346-8a354100-ab3e-11eb-815f-df52df54303c.png">

I have the default config:

```
<?php

return [
    // filename to store the settings, each locale is stored in a separate file
    'file' => 'seotamic',

    // Social images asset container
    'container' => 'assets',

    // blueprints we dont add fields to
    'ignore_blueprints' => [],
];
```

My images are stores in `public/assets`. Is there something I have misconfigured? @martink635

**Comment by martink635** [comment]
Hmm, do you have the `assets` container (which is there by default) available?

If you removed/renamed the handle you need to change it in the config as well

**Comment by connor11528** [comment]
Ah okay, figured it out. I installed Statamic into an existing Laravel project so it wasn't there by default. Instead I had `content/assets/images.yaml` but no `content/assets/assets.yaml` as described [in the docs](https://statamic.dev/assets#containers). Switching to "images" `container => images` fixed it.

And my Images container is using the assets driver, just to make it a bit more confusing lol

```
title: Images
disk: assets
allow_uploads: true
create_folders: true
```
Thanks for publishing the package! Excited to get started with it and SEO all the things :)
